image: python:latest

stages:
  - test

test:
  stage: test
  script:
    - python ./branch/validate_branch_naming.py
    - python ./branch/validate_repo_naming.py
    - python ./branch/validate_pipeline_naming.py
    - python ./branch/validate_environment_naming.py
