# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: python:latest

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - echo "Your build and test goes here..."
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
      - step:
          name: 'Security scan'
          script:
            - echo "Your security scan goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
          -  python ./branch/validate_branch_naming.py
          - python ./environment/validate_environment_naming.py
          - echo "staging test successful"
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          -  python ./branch/validate_branch_naming.py
          - python ./environment/validate_environment_naming.py
          - echo "production successful"