name: Validate Branch Naming Convention

on:
  push:
    branches: [main]

jobs:
  validate_branch_name:
    runs-on: macos-latest
    
    env:
      CI_COMMIT_BRANCH: ${{ github.head_ref }}

    steps:
    - uses: actions/checkout@v3
      with:
        repository: Emma121288/UniProject
        path: UniProject
        set-safe-directory: 'false'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install configparser
        
    - name: Validate branch name
      run: |
        python ./branch/validate_branch_naming.py
